version: '3'

services:
  backend:
    container_name: django-api
    build:
      context: ./backend
      dockerfile: django.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  frontend:
    container_name: vue-frontend
    build:
      context: ./frontend
      dockerfile: front.dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./frontend:/home/app
    command: "npm run serve"